### ISSUE TITLE
Error message.

### ISSUE THREAD

**Issue by tickix** [clicketz/buff-overlay#2] opened 2022-09-03 05:11 UTC
Hi, I keep getting this error message. Bug fix would be much appreciated. Thanks!!

Message: Interface\AddOns\BuffOverlay\BuffOverlay.lua:461: attempt to compare nil with number
Time: Sat Sep  3 14:10:48 2022
Count: 7
Stack: Interface\AddOns\BuffOverlay\BuffOverlay.lua:461: attempt to compare nil with number
[string "=[C]"]: ?
[string "@Interface\AddOns\BuffOverlay\BuffOverlay.lua"]:461: in function <Interface\AddOns\BuffOverlay\BuffOverlay.lua:460>
[string "=[C]"]: in function `sort'
[string "@Interface\AddOns\BuffOverlay\BuffOverlay.lua"]:460: in function `ApplyOverlay'
[string "@Interface\AddOns\BuffOverlay\BuffOverlay.lua"]:497: in function <Interface\AddOns\BuffOverlay\BuffOverlay.lua:488>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@Interface_Wrath\FrameXML\CompactUnitFrame.lua"]:100: in function <Interface_Wrath\FrameXML\CompactUnitFrame.lua:53>

Locals:

**Comment by clicketz** [comment] 2022-09-03 05:21
Are you using the latest version, and did you make any changes to any lua file?

I cannot reproduce this error right now.

This was a problem with older versions of the addon. Try resetting your profile with `/bo reset` and add any new abilities you want through the "custom spells" tab (it'll persist through addon updates in the future) and let me know if that fixes the issue.

**Comment by clicketz** [comment] 2022-09-03 09:19
Should be fixed with 65a25e5

Please reopen the issue if you're still experiencing problems after updating.

**Closed as completed by clicketz** 2022-09-03 09:19 UTC
Labels: bug
